<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="About.aspx.cs" Inherits="About" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
    .auto-style16 {
        width: 100%;
    }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="auto-style16">
    <tr>
        <td>
            <asp:Image ID="Image2" runat="server" ImageUrl="~/Photo/COLLECTION.png" Width="100%" />
        </td>
    </tr>
    <tr>
        <td>
            <section class="elementor-section elementor-top-section elementor-element elementor-element-7f3cbd8 elementor-section-content-middle ot-traditional elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-element_type="section" data-id="7f3cbd8" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}" style="box-sizing: border-box; display: block; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; transition: background 0.3s ease 0s, border 0.3s ease 0s, border-radius 0.3s ease 0s, box-shadow 0.3s ease 0s; padding: 90px 0px; color: rgb(109, 109, 109); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <div class="elementor-container elementor-column-gap-extended" style="box-sizing: border-box; display: flex; margin-right: auto; margin-left: auto; position: relative; max-width: 1250px; padding: 0px 15px;">
                    <div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-9fc2569 ot-flex-column-vertical" data-element_type="column" data-id="9fc2569" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; min-height: 1px; display: flex; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 610px;">
                        <div class="elementor-widget-wrap elementor-element-populated" style="box-sizing: border-box; position: relative; width: 580px; flex-wrap: wrap; align-content: center; display: flex; padding: 0px 15px; margin: 0px 30px 0px 0px; --e-column-margin-right: 30px; --e-column-margin-left: 0px; align-items: center;">
                            <div class="elementor-element elementor-element-925ee15 elementor-widget elementor-widget-iheading" data-element_type="widget" data-id="925ee15" data-widget_type="iheading.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 550px; margin-bottom: 0px;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s); padding: 0px 0px 20px;">
                                    <div class="ot-heading" style="box-sizing: border-box;">
                                        <span style="box-sizing: border-box; font-size: 14px; font-weight: 800; color: rgb(90, 129, 15); position: relative; display: inline-block; margin-bottom: 2px; text-transform: uppercase;">// ABOUT US</span><h2 class="main-heading" style="box-sizing: border-box; font-family: Montserrat, sans-serif; font-weight: 800; line-height: 48px; margin: 0px; color: rgb(27, 29, 33); font-size: 36px;">The scenario today</h2>
                                    </div>
                                </div>
                            </div>
                            <div class="elementor-element elementor-element-5f326aa elementor-widget elementor-widget-text-editor" data-element_type="widget" data-id="5f326aa" data-widget_type="text-editor.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; color: rgb(109, 109, 109); font-family: &quot;Nunito Sans&quot;, sans-serif; font-weight: var( --e-global-typography-text-font-weight ); width: 550px; margin-bottom: 0px; text-align: justify;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s); padding: 0px 0px 40px;">
                                    With rapid advancements in science and technology, mass production is no longer an issue but the consequent rise in e-waste has now become a matter of concern. It has resulted in governments around the globe adopting different e-waste management laws to help curb it. In India, the laws to manage e-waste have been in place since 2011, and it mandates that only authorized dismantlers and recyclers collect e-waste.</div>
                            </div>
                            <div class="elementor-element elementor-element-37f4b4e elementor-widget elementor-widget-text-editor" data-element_type="widget" data-id="37f4b4e" data-widget_type="text-editor.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; color: rgb(109, 109, 109); font-family: &quot;Nunito Sans&quot;, sans-serif; font-weight: var( --e-global-typography-text-font-weight ); width: 550px; text-align: justify;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s); padding: 0px 0px 40px;">
                                    But recycling your waste, especially your e-waste can be a very tricky job. First of all, there is data security-related concerns. Secondly, several e-waste management companies lack transparency when it comes to their waste management process, last but not the least, there is also a concern related to pricing. If these concerns sound familiar to you then you have come to the right place.</div>
                            </div>
                        </div>
                    </div>
                    <div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-7564da8 ot-flex-column-vertical" data-element_type="column" data-id="7564da8" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; min-height: 1px; display: flex; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 610px;">
                        <div class="elementor-widget-wrap elementor-element-populated" style="box-sizing: border-box; position: relative; width: 610px; flex-wrap: wrap; align-content: center; display: flex; padding: 0px 15px; margin: 0px; --e-column-margin-right: 0px; --e-column-margin-left: 0px; align-items: center;">
                            <div class="elementor-element elementor-element-3b487e2 welsome_about_sec elementor-widget elementor-widget-image" data-element_type="widget" data-id="3b487e2" data-widget_type="image.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; text-align: center; width: 580px;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s); margin: 0px;">
                                    <img alt="The scenario today" class="attachment-full size-full wp-image-5687" decoding="async" fetchpriority="high" height="570" sizes="(max-width: 540px) 100vw, 540px" src="https://greentekreman.com/wp-content/uploads/2022/02/image1-home3-1.png" srcset="https://greentekreman.com/wp-content/uploads/2022/02/image1-home3-1.png 540w, https://greentekreman.com/wp-content/uploads/2022/02/image1-home3-1-284x300.png 284w" style="box-sizing: border-box; height: auto; max-width: 100%; border: none; vertical-align: middle; border-radius: 0px; box-shadow: none; display: inline-block;" width="540" /></div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="elementor-section elementor-top-section elementor-element elementor-element-2ef044d elementor-section-content-middle ot-traditional elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-element_type="section" data-id="2ef044d" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}" style="box-sizing: border-box; display: block; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; transition: background 0.3s ease 0s, border 0.3s ease 0s, border-radius 0.3s ease 0s, box-shadow 0.3s ease 0s; padding: 90px 0px; background-color: rgb(249, 249, 249); color: rgb(109, 109, 109); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <div class="elementor-container elementor-column-gap-extended" style="box-sizing: border-box; display: flex; margin-right: auto; margin-left: auto; position: relative; max-width: 1250px; padding: 0px 15px;">
                    <div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-5da9db7 ot-flex-column-vertical" data-element_type="column" data-id="5da9db7" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; min-height: 1px; display: flex; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 610px;">
                        <div class="elementor-widget-wrap elementor-element-populated" style="box-sizing: border-box; position: relative; width: 610px; flex-wrap: wrap; align-content: center; display: flex; padding: 0px 15px; margin: 0px; --e-column-margin-right: 0px; --e-column-margin-left: 0px; align-items: center;">
                            <div class="elementor-element elementor-element-b908d39 welsome_about_sec elementor-widget elementor-widget-image" data-element_type="widget" data-id="b908d39" data-widget_type="image.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; text-align: center; width: 580px;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s); margin: 0px;">
                                    <img alt="About GreenTek Reman" class="attachment-full size-full wp-image-5688" decoding="async" height="1000" sizes="(max-width: 952px) 100vw, 952px" src="https://greentekreman.com/wp-content/uploads/2022/02/image1-home1-2.png" srcset="https://greentekreman.com/wp-content/uploads/2022/02/image1-home1-2.png 952w, https://greentekreman.com/wp-content/uploads/2022/02/image1-home1-2-286x300.png 286w, https://greentekreman.com/wp-content/uploads/2022/02/image1-home1-2-768x807.png 768w, https://greentekreman.com/wp-content/uploads/2022/02/image1-home1-2-720x756.png 720w" style="box-sizing: border-box; height: auto; max-width: 100%; border: none; vertical-align: middle; border-radius: 0px; box-shadow: none; display: inline-block;" width="952" /></div>
                            </div>
                        </div>
                    </div>
                    <div class="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-786006c ot-flex-column-vertical" data-element_type="column" data-id="786006c" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; min-height: 1px; display: flex; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 610px;">
                        <div class="elementor-widget-wrap elementor-element-populated" style="box-sizing: border-box; position: relative; width: 580px; flex-wrap: wrap; align-content: center; display: flex; padding: 0px 15px; margin: 0px 30px 0px 0px; --e-column-margin-right: 30px; --e-column-margin-left: 0px; align-items: center;">
                            <div class="elementor-element elementor-element-cd31553 elementor-widget elementor-widget-iheading" data-element_type="widget" data-id="cd31553" data-widget_type="iheading.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 550px; margin-bottom: 0px;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s); padding: 0px 0px 20px;">
                                    <div class="ot-heading" style="box-sizing: border-box;">
                                        <span style="box-sizing: border-box; font-size: 14px; font-weight: 800; color: rgb(90, 129, 15); position: relative; display: inline-block; margin-bottom: 2px; text-transform: uppercase;">// YOU GENEREATE ! WE REGENERATE !</span><h2 class="main-heading" style="box-sizing: border-box; font-family: Montserrat, sans-serif; font-weight: 800; line-height: 48px; margin: 0px; color: rgb(27, 29, 33); font-size: 36px;">About TechTrash</h2>
                                    </div>
                                </div>
                            </div>
                            <div class="elementor-element elementor-element-2b0e7f3 elementor-widget elementor-widget-text-editor" data-element_type="widget" data-id="2b0e7f3" data-widget_type="text-editor.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; color: rgb(109, 109, 109); font-family: &quot;Nunito Sans&quot;, sans-serif; font-weight: var( --e-global-typography-text-font-weight ); width: 550px; text-align: justify;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s); padding: 0px 0px 40px;">
                                    <p style="box-sizing: border-box; margin: 0px 0px 20px;">
                                        TechTrash is at the forefront of the e-waste recycling industry, offering comprehensive solutions for the responsible disposal of electronic waste. With a commitment to sustainability, TechTrash collects and recycles old or unused electronics, preventing them from ending up in landfills. By recycling e-waste, TechTrash helps conserve natural resources and reduces the environmental impact of electronic products. They follow strict environmental guidelines and use advanced recycling techniques to ensure that e-waste is processed safely and efficiently. TechTrash&#39;s innovative approach to e-waste management not only benefits the environment but also promotes a circular economy by reintroducing valuable materials back into the production cycle. Their dedication to sustainability and environmental stewardship makes them a leader in the e-waste recycling industry.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="elementor-section elementor-top-section elementor-element elementor-element-a6aed31 our_visionMision  ot-traditional elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-element_type="section" data-id="a6aed31" style="box-sizing: border-box; display: block; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; border-style: solid; border-width: 1px 0px 0px; border-color: rgb(210, 210, 210); transition: background 0.3s ease 0s, border 0.3s ease 0s, border-radius 0.3s ease 0s, box-shadow 0.3s ease 0s; padding: 60px 0px; color: rgb(109, 109, 109); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <div class="elementor-container elementor-column-gap-default" style="box-sizing: border-box; display: flex; margin-right: auto; margin-left: auto; position: relative; max-width: 1250px; padding: 0px 15px;">
                    <div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-023d693 ot-flex-column-vertical" data-element_type="column" data-id="023d693" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; min-height: 1px; display: flex; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 406.663px;">
                        <div class="elementor-widget-wrap elementor-element-populated" style="box-sizing: border-box; position: relative; width: 406.663px; flex-wrap: wrap; align-content: flex-start; display: flex; padding-top: 0px; padding-right: 15px !important; padding-bottom: 0px; padding-left: 15px !important; border-style: solid; border-width: 0px 1px 0px 0px; border-color: rgb(210, 210, 210); transition: background 0.3s ease 0s, border 0.3s ease 0s, border-radius 0.3s ease 0s, box-shadow 0.3s ease 0s;">
                            <div class="elementor-element elementor-element-7b9ec9d elementor-position-top elementor-vertical-align-top elementor-widget elementor-widget-image-box" data-element_type="widget" data-id="7b9ec9d" data-widget_type="image-box.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 375.862px;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s);">
                                    <div class="elementor-image-box-wrapper" style="box-sizing: border-box; text-align: left; align-items: flex-start;">
                                        <figure class="elementor-image-box-img" style="margin: 0px 0px 15px; box-sizing: border-box; display: inline-block; width: 375.862px;">
                                            <img alt="GreenTek Reman - Mission" class="attachment-full size-full wp-image-3627" decoding="async" height="350" sizes="(max-width: 600px) 100vw, 600px" src="https://greentekreman.com/wp-content/uploads/2020/12/mission_img.jpg" srcset="https://greentekreman.com/wp-content/uploads/2020/12/mission_img.jpg 600w, https://greentekreman.com/wp-content/uploads/2020/12/mission_img-300x175.jpg 300w" style="box-sizing: border-box; height: auto; max-width: 100%; border: none; vertical-align: middle; border-radius: 0px; box-shadow: none; transition-duration: 0.3s;" width="600" /></figure>
                                        <div class="elementor-image-box-content" style="box-sizing: border-box; width: 375.862px;">
                                            <h3 class="elementor-image-box-title" style="box-sizing: border-box; font-family: Nunito, sans-serif; font-weight: 800; line-height: 1.2; margin: 0px 0px 10px; color: rgb(90, 130, 16); font-size: 30px;">Our Misison</h3>
                                            <p class="elementor-image-box-description" style="box-sizing: border-box; margin: 0px; color: var( --e-global-color-text ); font-family: Roboto, sans-serif; font-weight: 400;">
                                                It is our consistent endeavor to provide our clients with environmentally safe e-waste disposal solutions by navigating them through complex environmental regulations and guidelines. We aspire to achieve it by ensuring that the customer data is sanitized as per the international standards through state-of-the-art technology.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-a697dfb ot-flex-column-vertical" data-element_type="column" data-id="a697dfb" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; min-height: 1px; display: flex; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 406.663px;">
                        <div class="elementor-widget-wrap elementor-element-populated" style="box-sizing: border-box; position: relative; width: 406.663px; flex-wrap: wrap; align-content: flex-start; display: flex; padding-top: 0px; padding-right: 15px !important; padding-bottom: 0px; padding-left: 15px !important; border-style: solid; border-width: 0px 1px 0px 0px; border-color: rgb(210, 210, 210); transition: background 0.3s ease 0s, border 0.3s ease 0s, border-radius 0.3s ease 0s, box-shadow 0.3s ease 0s;">
                            <div class="elementor-element elementor-element-c2bb620 elementor-position-top elementor-vertical-align-top elementor-widget elementor-widget-image-box" data-element_type="widget" data-id="c2bb620" data-widget_type="image-box.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 375.862px;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s);">
                                    <div class="elementor-image-box-wrapper" style="box-sizing: border-box; text-align: left; align-items: flex-start;">
                                        <figure class="elementor-image-box-img" style="margin: 0px 0px 15px; box-sizing: border-box; display: inline-block; width: 375.862px;">
                                            <img alt="GreenTek Reman - Vision" class="attachment-full size-full wp-image-3630" decoding="async" height="350" loading="lazy" sizes="(max-width: 600px) 100vw, 600px" src="https://greentekreman.com/wp-content/uploads/2020/12/vison_img-1.jpg" srcset="https://greentekreman.com/wp-content/uploads/2020/12/vison_img-1.jpg 600w, https://greentekreman.com/wp-content/uploads/2020/12/vison_img-1-300x175.jpg 300w" style="box-sizing: border-box; height: auto; max-width: 100%; border: none; vertical-align: middle; border-radius: 0px; box-shadow: none; transition-duration: 0.3s;" width="600" /></figure>
                                        <div class="elementor-image-box-content" style="box-sizing: border-box; width: 375.862px;">
                                            <h3 class="elementor-image-box-title" style="box-sizing: border-box; font-family: Nunito, sans-serif; font-weight: 800; line-height: 1.2; margin: 0px 0px 10px; color: rgb(90, 130, 16); font-size: 30px;">Our Vision</h3>
                                            <p class="elementor-image-box-description" style="box-sizing: border-box; margin: 0px; color: var( --e-global-color-text ); font-family: Roboto, sans-serif; font-weight: 400;">
                                                The driving force behind all the work that we do is to ultimately contribute towards a green and peaceful world - an earth that is ecologically healthy and able to nurture life in all its diversity.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-0ebaa15 ot-flex-column-vertical" data-element_type="column" data-id="0ebaa15" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); position: relative; min-height: 1px; display: flex; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 406.663px;">
                        <div class="elementor-widget-wrap elementor-element-populated" style="box-sizing: border-box; position: relative; width: 406.663px; flex-wrap: wrap; align-content: flex-start; display: flex; padding-top: 0px; padding-right: 15px !important; padding-bottom: 0px; padding-left: 15px !important;">
                            <div class="elementor-element elementor-element-f944a2f elementor-position-top elementor-vertical-align-top elementor-widget elementor-widget-image-box" data-element_type="widget" data-id="f944a2f" data-widget_type="image-box.default" style="box-sizing: border-box; --flex-direction: initial; --flex-wrap: initial; --justify-content: initial; --align-items: initial; --align-content: initial; --gap: initial; --flex-basis: initial; --flex-grow: initial; --flex-shrink: initial; --order: initial; --align-self: initial; flex-basis: var(--flex-basis); flex-grow: var(--flex-grow); flex-shrink: var(--flex-shrink); order: var(--order); align-self: var(--align-self); flex-direction: var(--flex-direction); flex-wrap: var(--flex-wrap); justify-content: var(--justify-content); align-items: var(--align-items); align-content: var(--align-content); gap: var(--gap); position: relative; --swiper-theme-color: #000; --swiper-navigation-size: 44px; --swiper-pagination-bullet-size: 6px; --swiper-pagination-bullet-horizontal-gap: 6px; --widgets-spacing: 20px; width: 376.663px;">
                                <div class="elementor-widget-container" style="box-sizing: border-box; transition: background .3s,border .3s,border-radius .3s,box-shadow .3s,transform var(--e-transform-transition-duration,.4s);">
                                    <div class="elementor-image-box-wrapper" style="box-sizing: border-box; text-align: left; align-items: flex-start;">
                                        <figure class="elementor-image-box-img" style="margin: 0px 0px 15px; box-sizing: border-box; display: inline-block; width: 376.663px;">
                                            <img alt="GreenTek Reman - Values" class="attachment-full size-full wp-image-3632" decoding="async" height="350" loading="lazy" sizes="(max-width: 600px) 100vw, 600px" src="https://greentekreman.com/wp-content/uploads/2020/12/values_img-1.jpg" srcset="https://greentekreman.com/wp-content/uploads/2020/12/values_img-1.jpg 600w, https://greentekreman.com/wp-content/uploads/2020/12/values_img-1-300x175.jpg 300w" style="box-sizing: border-box; height: auto; max-width: 100%; border: none; vertical-align: middle; border-radius: 0px; box-shadow: none; transition-duration: 0.3s;" width="600" /></figure>
                                        <div class="elementor-image-box-content" style="box-sizing: border-box; width: 376.663px;">
                                            <h3 class="elementor-image-box-title" style="box-sizing: border-box; font-family: Nunito, sans-serif; font-weight: 800; line-height: 1.2; margin: 0px 0px 10px; color: rgb(90, 130, 16); font-size: 30px;">Values (H.O.P.E)</h3>
                                            <p class="elementor-image-box-description" style="box-sizing: border-box; margin: 0px; color: var( --e-global-color-text ); font-family: Roboto, sans-serif; font-weight: 400;">
                                                The 4 core values that forms the foundation of our organization can be abbreviated to H.O.P.E</p>
                                            <ol style="box-sizing: border-box; margin: 0px 0px 20px; padding-left: 18px; list-style: decimal;">
                                                <li style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: bold;">H</b>umble in our actions.</li>
                                                <li style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: bold;">O</b>pen to feedback from our customers and team members.</li>
                                                <li style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: bold;">P</b>reserve in carrying out our responsibilities.</li>
                                                <li style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: bold;">E</b>nergy is always high when it comes to our attitude towards our work.</li>
                                            </ol>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </td>
    </tr>
    <tr>
        <td style="font-size:30px"><center>To Get Acess to the Admin Portal
            <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/admin_login.aspx">Click Me</asp:HyperLink></center>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
</table>
</asp:Content>

